//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanetler
    {
        public int No { get; set; }
        public Nullable<int> uyeNo { get; set; }
        public Nullable<int> kitapNo { get; set; }
        public Nullable<System.DateTime> emanetVermeTarih { get; set; }
        public Nullable<System.DateTime> emanetAlmaTarih { get; set; }
        public Nullable<System.DateTime> emanetIslemTarih { get; set; }
        public string emanetNot { get; set; }
        public string emanetTeslimDurumu { get; set; }
    
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
