//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public Kitaplar()
        {
            this.Emanetler = new HashSet<Emanetler>();
        }
    
        public int No { get; set; }
        public string kitapAd { get; set; }
        public Nullable<int> yazarNo { get; set; }
        public Nullable<int> kitapBaskiYil { get; set; }
        public Nullable<int> kitapSayfaSayi { get; set; }
        public Nullable<int> dilNo { get; set; }
        public Nullable<int> yayinEviNo { get; set; }
        public string kitapAciklama { get; set; }
        public Nullable<int> turNo { get; set; }
    
        public virtual Diller Diller { get; set; }
        public virtual ICollection<Emanetler> Emanetler { get; set; }
        public virtual Tur Tur { get; set; }
        public virtual Yayınevi Yayınevi { get; set; }
        public virtual Yazarlar Yazarlar { get; set; }
    }
}
