//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Vize
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kutuphane_VizeEntities1 : DbContext
    {
        public Kutuphane_VizeEntities1()
            : base("name=Kutuphane_VizeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Diller> Diller { get; set; }
        public DbSet<Emanetler> Emanetler { get; set; }
        public DbSet<Kitaplar> Kitaplar { get; set; }
        public DbSet<Okullar> Okullar { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tur> Tur { get; set; }
        public DbSet<Uyeler> Uyeler { get; set; }
        public DbSet<Yayınevi> Yayınevi { get; set; }
        public DbSet<Yazarlar> Yazarlar { get; set; }
    }
}
