//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyeler
    {
        public Uyeler()
        {
            this.Emanetler = new HashSet<Emanetler>();
        }
    
        public int No { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public string uyeTelefon { get; set; }
        public string uyeEposta { get; set; }
        public string uyeAdres { get; set; }
        public Nullable<int> okulNo { get; set; }
    
        public virtual ICollection<Emanetler> Emanetler { get; set; }
        public virtual Okullar Okullar { get; set; }
    }
}
