//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazarlar
    {
        public Yazarlar()
        {
            this.Kitaplar = new HashSet<Kitaplar>();
        }
    
        public int No { get; set; }
        public string yazarAd { get; set; }
        public string yazarSoyad { get; set; }
    
        public virtual ICollection<Kitaplar> Kitaplar { get; set; }
    }
}
